-- Query 1

SELECT 
	Sp.SUPPLIER_NAME,
    T.TIME_ID AS DATE, 
    T.QUARTER, 
    T.MONTH, 
    ROUND(SUM(S.TOTAL_SALE),2) AS TOTAL_SALE
FROM
	PRODUCTS P, SUPPLIERS SP, TIME T, SALES S
WHERE
		S.TIME_ID = T.TIME_ID AND
        S.PRODUCT_ID = P.PRODUCT_ID AND
        S.SUPPLIER_ID = Sp.SUPPLIER_ID
GROUP BY 
	Sp.SUPPLIER_NAME, T.QUARTER, T.MONTH
ORDER BY
	DATE ASC;
	
	
-- Query 2

SELECT 
	 St.STORE_NAME, 
     P.PRODUCT_NAME, 
     ROUND(SUM(S.TOTAL_SALE),2) AS TOTAL_SALE
FROM
	PRODUCTS P, STORES St, SALES S
WHERE
        S.PRODUCT_ID = P.PRODUCT_ID AND
        S.STORE_ID = St.STORE_ID
GROUP BY 
	St.STORE_NAME,P.PRODUCT_ID, P.PRODUCT_NAME;

-- Query 3

SELECT 
	S.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    SUM(S.Quantity) AS NUMBER_OF_SALES
FROM
	PRODUCTS P, SALES S
WHERE
        S.PRODUCT_ID = P.PRODUCT_ID AND 
			(
				dayname(S.TIME_ID)  LIKE 'Saturday' OR
				dayname(S.TIME_ID)  LIKE 'Sunday'               
			)
GROUP BY 
	S.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 
	NUMBER_OF_SALES DESC
LIMIT 
	5;
	
-- Query 4

SELECT 
	S.PRODUCT_ID, 
    P.PRODUCT_NAME,
    ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 1)
            THEN S.TOTAL_SALE END),2) AS FIRST_QUARTER_SALES,
	ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 2)
            THEN S.TOTAL_SALE END),2) AS SECOND_QUARTER_SALES,
    ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 3)
            THEN S.TOTAL_SALE END),2) AS THIRD_QUARTER_SALES,
	ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 4)
            THEN S.TOTAL_SALE END),2) AS FOURTH_QUARTER_SALES,
	ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 1 OR T.QUARTER = 2 OR T.QUARTER = 3 OR T.QUARTER = 4)
            THEN S.TOTAL_SALE END),2) AS TOTAL_YEARLY_SALES
FROM 
	SALES S, TIME T, PRODUCTS P
WHERE 
	S.TIME_ID = T.TIME_ID AND
    S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 
	S.PRODUCT_ID
ORDER BY
	S.PRODUCT_ID;

-- Query 5

SELECT 
	S.PRODUCT_ID, 
    P.PRODUCT_NAME,
    ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 1 OR T.QUARTER = 2)
            THEN S.TOTAL_SALE END),2) AS FIRST_HALF_SALES,
	ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 3 OR T.QUARTER = 4)
            THEN S.TOTAL_SALE END),2) AS SECOND_HALF_SALES,
	ROUND(SUM(
		CASE 
			WHEN (T.QUARTER = 1 OR T.QUARTER = 2 OR T.QUARTER = 3 OR T.QUARTER = 4)
            THEN S.TOTAL_SALE END),2) AS TOTAL_YEARLY_SALES
FROM 
	SALES S, TIME T, PRODUCTS P
WHERE 
	S.TIME_ID = T.TIME_ID AND
	S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 
	S.PRODUCT_ID;


-- Query 6

SELECT 
	DISTINCT(T.PRODUCT_ID), 
    M.PRODUCT_NAME, 
    M.PRICE, 
    M.SUPPLIER_ID
FROM
	TRANSACTIONS T, MASTERDATA M
WHERE
	M.PRODUCT_ID = T.PRODUCT_ID AND
	M.PRODUCT_NAME LIKE 'TOMATOES';

-- Query 7

CREATE OR REPLACE VIEW STOREANALYSIS_MV AS (
	SELECT 
		 St.STORE_NAME, 
         P.PRODUCT_NAME, 
         ROUND(SUM(S.TOTAL_SALE),2) AS TOTAL_SALE
	FROM
		PRODUCTS P, STORES St, SALES S
	WHERE
			S.PRODUCT_ID = P.PRODUCT_ID AND
			S.STORE_ID = St.STORE_ID
	GROUP BY 
		St.STORE_NAME,P.PRODUCT_ID, P.PRODUCT_NAME
);